<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LP1-AP-51860169" ignored="0" name="login" tests="2" failures="1" timestamp="03 May 2021 13:25:04 GMT" time="22.33" errors="0">
  <testcase name="crmLogoImageTest" time="3.393" classname="com.crm.qa.LoginPageTest"/>
  <testcase name="loginPageTitleTest" time="1.486" classname="com.crm.qa.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [#1 Free CRM customer relationship management software cloud] but found [Cogmento CRM]">
      <![CDATA[java.lang.AssertionError: expected [#1 Free CRM customer relationship management software cloud] but found [Cogmento CRM]
	at com.crm.qa.LoginPageTest.loginPageTitleTest(LoginPageTest.java:34)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
</testsuite> <!-- login -->
